name: Terraform Drift Detection and Reconciliation

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight

jobs:
  # Detect drift in the main branch
  detect-drift:
    name: Detect Drift
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0

      - name: Terraform init
        run: terraform init

      - name: Terraform plan
        id: plan
        run: terraform plan -out=tfplan -detailed-exitcode || echo "Plan failed with exit code $?"

  # Notify on drift detection (optional)
  notify-on-drift:
    name: Notify on Drift (if detected)
    runs-on: ubuntu-latest
    if: steps.detect-drift.outputs.exitcode == '2'  # Only run if drift detected
    steps:
       - name: Send Email Notification
         run: |
          echo "Drift detected! Please review the plan file." | mail -s "Terraform Drift Detected" priyankatuladhar14@gmail.com


  # Reconcile drift 
  reconcile-changes:
    name: Reconcile Changes (Manual Review Recommended)
    runs-on: ubuntu-latest
    if: steps.detect-drift.outputs.exitcode == '2'  # Only run if drift detected
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0

      - name: Terraform plan with verbose output
        run: terraform plan -out=tfplan

      - name: Apply changes 
        run: terraform apply -auto-approve
